### ISSUE TITLE
OptionsError: No options have been set

### ISSUE THREAD

**Issue by fiesh** [vim-vdebug/vdebug#12]
I am using vdebug on a PHP project, and sometimes I cannot set breakpoints any more.  Restarting vim helps.  I do not know what triggers this, initially I can set breakpoints but from some point onwards the following happens:

An error occured: <class 'vdebug.opts.OptionsError'>  
Traceback (most recent call last):
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 111, in set_breakpoint
    self.runner.set_breakpoint(args)
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 184, in set_breakpoint
    bp = vdebug.breakpoint.Breakpoint.parse(self.ui,args)
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/vdebug/breakpoint.py", line 107, in parse
    file = ui.get_current_file()
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 76, in get_current_file
    return vdebug.util.FilePath(vim.current.buffer.name)
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/vdebug/util.py", line 13, in **init**
    self.local = self._create_local(filename)
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/vdebug/util.py", line 22, in _create_local
    if vdebug.opts.Options.isset('remote_path'):
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/vdebug/opts.py", line 41, in isset
    inst = cls.inst()
  File "/home/fiesh/.vim/bundle/vdebug/plugin/python/vdebug/opts.py", line 19, in inst
    raise OptionsError, "No options have been set"
OptionsError: No options have been set

**Comment by zeeshanjan82** [comment]
@yargy were you able to resolve this issue. I am facing the same issue.

**Comment by cincodenada** [comment]
@zeeshanjan82 Can you paste the relevant lines of your `.vimrc`? In theory, supplying the whole dictionary should work (and does on my copy), but here's a more foolproof way of setting Vdebug options that may work if that way does not:

    if !exists('g:vdebug_options')
        let g:vdebug_options = {}
    endif
    let g:vdebug_options['break_on_open'] = 0
    let g:vdebug_options['watch_window_style': 'compact']

That should work reliably if there are some odd loading-order issues involved.

Also, I doubt this will be of help to @yargy three years later, but their syntax above is incorrect, as the `break_on_open` option will be overwritten, because the second `let` re-defines the whole dictionary without that key. There are two ways to set vdebug_options: setting individual keys with the bracket notation, as above, or setting the whole dictionary at once. Setting the whole dictionary multiple times will cause problems.

Note that if using the whole dictionary, re-sourcing the `.vimrc` will break Vdebug, as it recreates `vdebug_options` without the defaults, and Vdebug has no chance to add the defaults as it does at startup.
