### ISSUE TITLE
debugger suddenly stopped working

### ISSUE THREAD

**Issue by sant527** [vim-vdebug/vdebug#180]
```
Waiting for a connection (Ctrl-C to cancel, this message will self-destruct in  20  seconds...)
An error occured: <class 'vim.error'>
Traceback (most recent call last):
  File "/home/simha/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "/home/simha/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 160, in run
    self.open()
  File "/home/simha/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 47, in open
    self.ui.open()
  File "/home/simha/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 75, in open
    raise e
error: Vim(new):E325: ATTENTION
```

till yesterday debugger was working. 
today suddenly after pressing f5. it doesnt show up anything
when i press enter it shows the message above.

**Comment by dkinzer** [comment]
Nice this helped me too, after an hour of trying to figure out what was going on.  Wish the error had given a hint about possible fixes.

**Comment by joonty** [comment]
@dkinzer take a look at https://github.com/joonty/vdebug/issues/187 - this is something I plan to introduce in version 2.

Thanks

**Comment by dkinzer** [comment]
@joonty thanks!
