### ISSUE TITLE
:python3 is not available, macvim

### ISSUE THREAD

**Issue by Dudemullet** [vim-vdebug/vdebug#329]
Whenever I open macvim, I see the following error

>:python3 is not available, vdebug will not be loaded.

OS is:
`macOS High Sierra 10.13.3`

and I'm sure I have python3 installed 

>$ python3 --version
>`Python 3.6.4`

>$ python --version
>`Python 3.6.4`

Here is `mvim --version` output
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 18 2018 04:09:42)
macOS version
Included patches: 1-1522
Compiled by root@Traviss-Mac-913.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_netterm     +tag_binary
+arabic            +file_in_path      +mouse_sgr         +tag_old_static
+autocmd           +find_in_path      -mouse_sysmouse    -tag_any_white
-autoservername    +float             +mouse_urxvt       -tcl
+balloon_eval      +folding           +mouse_xterm       +termguicolors
+balloon_eval_term -footer            +multi_byte        +terminal
+browse            +fork()            +multi_lang        +terminfo
++builtin_terms    +fullscreen        -mzscheme          +termresponse
+byte_offset       -gettext           +netbeans_intg     +textobjects
+channel           -hangul_input      +num64             +timers
+cindent           +iconv             +odbeditor         +title
+clientserver      +insert_expand     +packages          +toolbar
+clipboard         +job               +path_extra        +transparency
+cmdline_compl     +jumplist          +perl/dyn          +user_commands
+cmdline_hist      +keymap            +persistent_undo   +vertsplit
+cmdline_info      +lambda            +postscript        +virtualedit
+comments          +langmap           +printer           +visual
+conceal           +libcall           +profile           +visualextra
+cryptv            +linebreak         +python/dyn        +viminfo
+cscope            +lispindent        +python3/dyn       +vreplace
+cursorbind        +listcmds          +quickfix          +wildignore
+cursorshape       +localmap          +reltime           +wildmenu
+dialog_con_gui    +lua/dyn           +rightleft         +windows
+diff              +menu              +ruby/dyn          +writebackup
+digraphs          +mksession         +scrollbind        -X11
+dnd               +modify_fname      +signs             -xfontset
-ebcdic            +mouse             +smartindent       +xim
+emacs_tags        +mouseshape        +startuptime       -xpm
+eval              +mouse_dec         +statusline        -xsmp
+ex_extra          -mouse_gpm         -sun_workshop      -xterm_clipboard
+extra_search      -mouse_jsbterm     +syntax            -xterm_save
```

**Comment by BlackIkeEagle** [comment]
I'm not sure if you can find what python version mvim was compiled against? Although you have `+python3/dyn` you still can get issues if the python version mvim was compiled with differs a lot from the python version you have installed

**Comment by markwu** [comment]
Even you compiled MacVim with python and python3 support, you only can run one of them  in one vim session.

```
+python/dyn
+python3/dyn 
```

I guess you have other plugins run python2 first, then you have no chance to run python3.

Your can try put the following code in the beginning of your `.vimrc`, to make vim run python3 first. But you may see some errors if your other plugin does not support python3 or compiled with python2, you have to recompile those plugin again.

```
call has('python3')
```

After that, you can use `:echo has('python3')` to test if python3 running, it should be return `1`.

If you want both of python2/python3 run in the same session, you have to compile MacVim with PyDev (See wiki in MacVim) or use Neovim.

**Comment by lukevers** [comment]
I had this same issue today as @Dudemullet after upgrading my vdebug vim plugin and what I did was upgrade MacVim (`brew upgrade macvim`) and now I have:

```
-python
+python3
```

and now it loads, but then I have other issues. 

Whenever I close macvim, even if I never used vdebug, this occurs:

```log
Vdebug is not running
Exception ignored in: <bound method Window.__del__ of <vdebug.ui.vimui.WatchWindow object at 0x6fa20b8>>
Traceback (most recent call last):
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/interface.py", line 37, in __del__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 495, in destroy
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 379, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 110, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 115, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 28, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 101, in _actual_log
ValueError: I/O operation on closed file.
Exception ignored in: <bound method Window.__del__ of <vdebug.ui.vimui.StackWindow object at 0x6fb8470>>
Traceback (most recent call last):
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/interface.py", line 37, in __del__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 495, in destroy
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 379, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 110, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 115, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 28, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 101, in _actual_log
ValueError: I/O operation on closed file.
Exception ignored in: <bound method Window.__del__ of <vdebug.ui.vimui.StatusWindow object at 0x6ff0240>>
Traceback (most recent call last):
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/interface.py", line 37, in __del__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 495, in destroy
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 379, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 110, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 115, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 28, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 101, in _actual_log
ValueError: I/O operation on closed file.
Exception ignored in: <bound method Window.__del__ of <vdebug.ui.vimui.BreakpointWindow object at 0x7195ef0>>
Traceback (most recent call last):
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/interface.py", line 37, in __del__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 495, in destroy
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 379, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 110, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 115, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 28, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 101, in _actual_log
ValueError: I/O operation on closed file.
Exception ignored in: <bound method Window.__del__ of <vdebug.ui.vimui.LogWindow object at 0x7195f98>>
Traceback (most recent call last):
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/interface.py", line 37, in __del__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 495, in destroy
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 379, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 110, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 115, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 28, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 101, in _actual_log
ValueError: I/O operation on closed file.
Exception ignored in: <bound method Window.__del__ of <vdebug.ui.vimui.TraceWindow object at 0x719f048>>
Traceback (most recent call last):
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/interface.py", line 37, in __del__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 495, in destroy
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/ui/vimui.py", line 379, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 110, in __init__
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 115, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 28, in log
  File "/Users/lukevers/.vim/bundle/vdebug/pythonx/vdebug/log.py", line 101, in _actual_log
ValueError: I/O operation on closed file.
```

If I try to run vdebug, it connects, but this happens:

<img width="1788" alt="screen shot 2018-03-29 at 9 46 19 am" src="https://user-images.githubusercontent.com/1558388/38092378-18488436-3336-11e8-9e65-6719f887da2b.png">

here's my log:

```log
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerWatch: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerStack: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerStatus: []
- [Info] {Thu 29 2018 09:46:18} Found connection from ('172.28.128.3', 50779)
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Debug] {Thu 29 2018 09:46:18} Setting buffer for DebuggerLog: []
- [Info] {Thu 29 2018 09:46:18} Closing the connection
```

**Comment by lukevers** [comment]
Fixed my issue after talking on IRC about it. I had these in my vimrc for `g:vedebug_options`

```vim
    \    "debug_window_level" : 2,
    \    "debug_file_level" : 2,
```

the first one fixed my issue with the multiple debugger log buffers opening and ruining my screen, and the second one fixed my stacktrace on exit. I still get "Vdebug is not running" but everything else seems to work.

Sorry for hijacking this thread, I thought I might have been having the same problems.

**Comment by BlackIkeEagle** [comment]
Since I now have tested both cli and macvim on macos I'll close this
