### ISSUE TITLE
Error on breakpoint

### ISSUE THREAD

**Issue by kviolka** [vim-vdebug/vdebug#345]
I get the following error when the debugger activates on some breakpoints in my PHP project:

I'm using the current master with vim 8.0.0197 on Debian Stretch.

- [ERROR] {Sa 07 2018 21:11:07} An error occured: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/k4v/.vim/bundle/vdebug/pythonx/vdebug/event.py", line 524, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/k4v/.vim/bundle/vdebug/pythonx/vdebug/event.py", line 262, in run
    if str(status) == "interactive":
TypeError: __str__ returned non-string (type NoneType)

**Comment by BlackIkeEagle** [comment]
@kviolka would it be hard for you to create a minimal test where you can reproduce this issue, or a description of what exactly you do to trigger this issue? And if you could add a vdebug.log file where `debug_file_level` is set to 2.

**Comment by robertjk** [comment]
I have a similar error

```
- [ERROR] {mié 06 2019 15:37:25} An error occured: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/robert/.vim/plug-bundle/vdebug/python3/vdebug/event.py", line 522, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/robert/.vim/plug-bundle/vdebug/python3/vdebug/event.py", line 260, in run
    if str(status) == "interactive":
TypeError: __str__ returned non-string (type NoneType)
```

Am not able to give steps to reproduce the error, but can include the log with `debug_file_level` set to 2: https://pastecode.xyz/view/5672bcde
