### ISSUE TITLE
`set langmap` with non ascii characters causes vdebug to exit with: Error starting Vdebug: <class 'UnicodeDecodeError'> 

### ISSUE THREAD

**Issue by nexusstar** [vim-vdebug/vdebug#350]
I am using Neovim v0.2.2 on **Windows 10 (WLS Kali installed)** running on command prompt 
**OS**
 `Linux Q306 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux`

**vdebug**
master -> 5e1d263424283eb5b735e9efc933ca31a0ec0672

In my configuration files I've got: 
```
set langmap=ч`,яq,вw,еe,рr,тt,ъy,уu,иi,оo,пp,ш[,щ],аa,сs,дd,фf,гg,хh,йj,кk,лl,;;,'',ю\\,зz,ьx,цc,жv,бb,нn,мm,Ч~,ЯQ,ВW,ЕE,РR,ТT,ЪY,УU,ИI,ОO,ПP,Ш{,Щ},АA,СS,ДD,ФF,ГG,ХH,ЙJ,КK,ЛL,::,"",Ю|,ЗZ,ѝX,ЦC,ЖV,БB,НN,МM,„<,“>
```
which causes  following error when all configuration and plugins are enabled:
```
debug will wait for a connection in the background
Found connection, starting debugger
Error starting Vdebug: <class 'UnicodeDecodeError'>
```
If I leave only this one I receive following errors:
```
Found connection, starting debugger
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nexus/.config/nvim/plugged/vdebug/pythonx/vdebug/debugger_interface.py", line 47, in run
    self.session_handler.run()
  File "/home/nexus/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 67, in run
    self.listen()
  File "/home/nexus/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 42, in listen
    self.__new_session()
  File "/home/nexus/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 120, in __new_session
    status = self.__session.start(self.listener.create_connection())
  File "/home/nexus/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 202, in start
    self.__keymapper.map()
  File "/home/nexus/.config/nvim/plugged/vdebug/pythonx/vdebug/util.py", line 130, in map
    self._store_old_map()
  File "/home/nexus/.config/nvim/plugged/vdebug/pythonx/vdebug/util.py", line 160, in _store_old_map
    for line in codecs.open(tempfile, 'r', errors='ignore'):
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 4984: invalid continuation byte
```

~~I check with the same configuration in Ubuntu 16.04 and there is no problem.~~

**Comment by BlackIkeEagle** [comment]
@nexusstar So is this reproducable on ubuntu? or is this specific to the linux subsystem on windows?

**Comment by BlackIkeEagle** [comment]
@nexusstar ok I can reproduce this. I'm trying to figure out how to solve this

**Comment by nexusstar** [comment]
@BlackIkeEagle sorry for the late replay and  yes I manage to reproduce it on Ubuntu.

**Comment by BlackIkeEagle** [comment]
@nexusstar no worries, I can reproduce it and am trying to find a solution. The solution is not as trivial as first thought :(
