### ISSUE TITLE
Type Error when I try to set a breakpoint in a Drupal controller.

### ISSUE THREAD

**Issue by kviolka** [vim-vdebug/vdebug#362]
- [ERROR] {Sa 09 2018 18:11:31} An error occured: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/k4v/.vim/bundle/vdebug/pythonx/vdebug/event.py", line 524, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/k4v/.vim/bundle/vdebug/pythonx/vdebug/event.py", line 262, in run
    if str(status) == "interactive":
TypeError: __str__ returned non-string (type NoneType)

**Comment by Raensul** [comment]
There is a new one connected to the fix.

```
An error occured: <class 'TypeError'>
Traceback (most recent call last):
  File "/Users/rnsl/.vim/bundle/vdebug/python3/vdebug/event.py", line 722, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/Users/rnsl/.vim/bundle/vdebug/python3/vdebug/event.py", line 275, in run
    status_str = str(status)
TypeError: __str__ returned non-string (type NoneType)
```

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 26 2019 21:43:31)
macOS version
Included patches: 1-2350
Compiled by Homebrew
```
