### ISSUE TITLE
empty buffer on breakpoint

### ISSUE THREAD

**Issue by Fandekasp** [vim-vdebug/vdebug#365]
Following the installation (https://github.com/vim-vdebug/vdebug/issues/361), here's what I get when php reaches the `xdebug_breakpoint()`

![](https://i.imgur.com/eV8Mzol.png)

@BlackIkeEagle any idea why I get an empty buffer ? instead of seeing the file where the breakpoint was ?

I'm so confused as to how we're supposed to use vdebug, and lot of errors keep popping up

For example: 
* I type `:Breakpoint` on a line
* I type `:BreakpointWindow` to see the id of my breakpoint
* I type `:BreakpointRemove 11000` to remove the breakpoint
⇒ getting the following error
```
- [ERROR] {Thu 14 2018 10:39:21} An error occured: <class 'neovim.api.nvim.NvimError'>
Traceback (most recent call last):
  File "/home/dori/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 524, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/dori/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 422, in run
    self.session_handler.breakpoints().remove_breakpoint_by_id(id)
  File "/home/dori/.vim/plugged/vdebug/pythonx/vdebug/breakpoint.py", line 56, in remove_breakpoint_by_id
    self.breakpoints[id].on_remove()
  File "/home/dori/.vim/plugged/vdebug/pythonx/vdebug/breakpoint.py", line 107, in on_remove
    self.ui.remove_breakpoint(self)
  File "/home/dori/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 203, in remove_breakpoint
    self.windows.breakpoints().remove_breakpoint(id)
neovim.api.nvim.NvimError: b'Index out of bounds'
``` 

When I press <F5> to continue the code execution, my page is shown. After typing <F6> to close vdebug, the vdebug panes don't close. When trying to close them manually, I get
![](https://i.imgur.com/BkaoxsH.png)

**Comment by Fandekasp** [comment]
I had forgotten to set the `let g:vdebug_options.path_maps` to match remote and host files.
