### ISSUE TITLE
vdebug + xdebug + nvim = closing connection

### ISSUE THREAD

**Issue by cprn** [vim-vdebug/vdebug#376]
Hi. I used `vdebug` with `xdebug` long time ago, now updated everything, tried again and it doesn't work. Symptoms from the user's point of view:

1. On Ubuntu 18.04.1 I install `php5.6` from `ppa:ondrej/php` and then `php-xdebug`
1. call `sudo phpenmod xdebug` and check the `php -v` output:
```
PHP 5.6.37-1+ubuntu18.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
3. I run NVIM v0.2.2, install `vdebug` with `vim-plug`
1. I open some PHP test file, set a break point, press F5, see:
`Vdebug will wait for a connection in the background`
and the following in the log file:
```
- [Debug] {Mon 06 2018 15:24:41} Started
- [Debug] {Mon 06 2018 15:24:41} Listening on port 9000
```
1. in separate terminal window I run `phpunit`, everything hangs
1. nothing happens unless I switch to vim and press enter, then I see:
`Found connection, starting debugger`
and the following in the log file (it overwrites previous content):
```
- [Debug] {Mon 06 2018 15:27:26} Found client, ('127.0.0.1', 33910)
- [Debug] {Mon 06 2018 15:27:26} Finishing socket server
```
6. again, nothing else happens until I press enter, then the debugger view opens but `vdebug` is not running and I see the following in the log file:
```
- [Debug] {Mon 06 2018 15:28:57} Setting buffer for DebuggerWatch: ['']
- [Info] {Mon 06 2018 15:31:12} Closing the connection
- [Debug] {Mon 06 2018 15:31:12} Command: stop -i 1
- [Debug] {Mon 06 2018 15:31:12} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="1" status="stopped" reason="ok"></response>
- [Debug] {Mon 06 2018 15:31:12} Closing the socket
- [Debug] {Mon 06 2018 15:31:12} Closing the socket
- [Debug] {Mon 06 2018 15:31:12} keymapper: unmap
- [Debug] {Mon 06 2018 15:31:12} Closing the socket
```

Any advice? Steps to further debug this? Why does the connection close?

**Comment by choicelildice** [comment]
This is also happening for me, same log. Did you find a solution @cprn ?

**Comment by cprn** [comment]
@choicelildice Nope, I'm still struggling with this. Using a different IDE for debugging in the mean time.

**Comment by BlackIkeEagle** [comment]
@cprn is there a way for you to update to the latest version of nvim ?

**Comment by cprn** [comment]
@BlackIkeEagle Awesome! Installed `NVIM 0.3.0` via PPA and it works! I still have to press something to "refresh" the view and see the connection actually established but other than that, it's perfectly usable. I also have a minor issue when trying to close superglobal variable tree in DebuggerWatch (pasting output here in case I forget about it) but I need to go through tickets here and prepare minimal case before I post a separate issue.

```viml
Error detected while processing function provider#python3#Call:                                                                                                                                                                       
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/debugger_interface.py", line 72, in handle_return_keypress
    return self.event_dispatcher.by_position(self.session_handler)
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/event.py", line 541, in by_position
    return event.run()
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/event.py", line 178, in run
    self.ui.windows.watch().delete(lineno, end_lineno+1)
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 461, in delete
    self._buffer.delete(start_line, end_line)
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 353, in delete
    self._buffer[end_line]
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Index out of bounds'
Press ENTER or type command to continue
```

**Comment by cprn** [comment]
@BlackIkeEagle Awesome! Installed `NVIM 0.3.0` via PPA and it works! I still have to press something to "refresh" the view and see the connection actually established but other than that, it's perfectly usable. I also have a minor issue when trying to close superglobal variable tree in DebuggerWatch (pasting output here in case I forget about it) but I need to go through tickets here and prepare minimal case before I post a separate issue.

```viml
Error detected while processing function provider#python3#Call:                                                                                                                                                                       
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/debugger_interface.py", line 72, in handle_return_keypress
    return self.event_dispatcher.by_position(self.session_handler)
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/event.py", line 541, in by_position
    return event.run()
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/event.py", line 178, in run
    self.ui.windows.watch().delete(lineno, end_lineno+1)
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 461, in delete
    self._buffer.delete(start_line, end_line)
  File "/home/mg/.config/nvim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 353, in delete
    self._buffer[end_line]
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/mg/.local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Index out of bounds'
Press ENTER or type command to continue
```
