### ISSUE TITLE
Error when installing with Vundle

### ISSUE THREAD

**Issue by AFakeman** [vim-vdebug/vdebug#391]
Added a `Plugin 'vim-vdebug/vdebug'` line and ran `:PluginInstall`. This was the output I got for some reason. Other python3 plugins work (python3 is installed with brew).

```
Error detected while processing /Users/anton/.config/vim/vim/bundle/vdebug/plugin/vdebug.vim:
line  110:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'vdebug'
line  111:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vdebug' is not defined
Error detected while processing function Vdebug_load_options:
line    8:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'debugger' is not defined
Error detected while processing function Vdebug_load_keymaps:
line   22:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'debugger' is not defined
```

**Comment by BlackIkeEagle** [comment]
@AFakeman could you provide a little more info? possibly the following:
- vim --version
- a minimal example .vimrc
- your version of macos and brew

**Comment by maysara** [comment]
I'm facing the same problem, on a debian sid, python3.6 install, vim --version reports +python3 , no .vimrc file ...

**Comment by kaisa316** [comment]
我也遇到了相同的问题，是新版的bug吗

**Comment by jazty** [comment]
I encountered this today after pulling the latest from the repo.
I'm not going to pretend to know why this happens or the proper way to fix it, but I was at least able to make it work by adding to  `plugin/vdebug.vim` at line 116:
`python3 import sys
python3 sys.path.insert(1, '/home/USERNAME/.vim/bundle/vdebug/python3')
python3 import vdebug.debugger_interface
python3 debugger = vdebug.debugger_interface.DebuggerInterface()
`
