### ISSUE TITLE
Index out of bound

### ISSUE THREAD

**Issue by Dornat** [vim-vdebug/vdebug#433]
Currently I'm trying to debug remote php project in docker. And it runs great but every time I want to see properties and open them by pressing enter there is an error that shows up constantly:

```python
Error detected while processing function provider#python3#Call:
line 18: Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dornat/.vim/plugged/vdebug/pythonx/vdebug/debugger_interface.py", line 72, in handle_return_keypress
    return self.event_dispatcher.by_position(self.session_handler)
  File "/home/dornat/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 543, in by_position
    return event.run()
  File "/home/dornat/.vim/plugged/vdebug/pythonx/vdebug/event.py", line 151, in run
    self.ui.windows.watch().delete(lineno, lineno+1)
  File "/home/dornat/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 465, in delete
    self._buffer.delete(start_line, end_line)
  File "/home/dornat/.vim/plugged/vdebug/pythonx/vdebug/ui/vimui.py", line 357, in delete
    self._buffer[end_line]
  File "/usr/lib/python3.8/site-packages/pynvim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/usr/lib/python3.8/site-packages/pynvim/api/common.py", line 58, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Index out of bounds
```

And in log file there is this stuff. 

```php
- [Debug] {Sun 01 2019 23:31:08} User action in watch window, line 40
- [Debug] {Sun 01 2019 23:31:08} ** WatchWindowPropertyGetEvent
- [Debug] {Sun 01 2019 23:31:08} Command: property_get -i 41 -n "$this->*Zenith\\Library\\Http\\Dispatcher\\DispatcherAbstract*_router" -d 0
- [Debug] {Sun 01 2019 23:31:09} Response: <?xml version="1.0" encoding="iso-8859-1"?> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="property_get" transaction_id="41"><property name="$this-&gt;*Zenith\Library\Http\Dispatcher\     DispatcherAbstract*_router" fullname="$this-&gt;*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router" type="object" classname="AltoRouter" children="1" numchildren="4" page="0" pagesi     ze="32"><property name="routes" fullname="$this-&gt;*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router-&gt;routes" facet="protected" type="array" children="1" numchildren="275"></pr     operty><property name="namedRoutes" fullname="$this-&gt;*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router-&gt;namedRoutes" facet="protected" type="array" children="1" numchildren="     275"></property><property name="basePath" fullname="$this-&gt;*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router-&gt;basePath" facet="protected" type="string" size="0" encoding="bas     e64"><![CDATA[]]></property><property name="matchTypes" fullname="$this-&gt;*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router-&gt;matchTypes" facet="protected" type="array" childre     n="1" numchildren="16"></property></property></response>
 - [Info] {Sun 01 2019 23:31:09} Writing 5 properties to the window
 - [Debug] {Sun 01 2019 23:31:09} Writing to window:
    ▾ $this->*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router = (AltoRouter [4])
      ▸ $this->*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router->routes = (array [275])
      ▸ $this->*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router->namedRoutes = (array [275])
      ⬦ $this->*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router->basePath = (string [0]) ``
      ▸ $this->*Zenith\Library\Http\Dispatcher\DispatcherAbstract*_router->matchTypes = (array [16])
```

Maybe this line that says about "writing 5 properties to the window" but an array has only 4 elements can be somehow connected to this. Just shot in the dark.

Don't know where else to look.

**Comment by gvanbeck** [comment]
+1

**Comment by BlackIkeEagle** [comment]
Thanks I'll have a look

**Comment by nacknime-official** [comment]
+1
I use pydbgp.

**Comment by Mte90** [comment]
![Screenshot_20200827_105715](https://user-images.githubusercontent.com/403283/91421420-37d8ad80-e856-11ea-9ee9-5d4e6193f409.png)
I got that today.

**Comment by Mte90** [comment]
![Screenshot_20200827_110703](https://user-images.githubusercontent.com/403283/91421758-9aca4480-e856-11ea-88f2-3c76c30e32ed.png)
![Screenshot_20200827_110754](https://user-images.githubusercontent.com/403283/91421761-9b62db00-e856-11ea-8178-6991c5b8a9b7.png)
I got also this error after this and issues on closing but I don't know if they are related

**Comment by nkoporec** [comment]
Have the same issue, when opening a larger array (php), any ideas on how to resolve this?  I'm having this issue while using neovim, if I switch to vim, it works normally.

**Comment by BlackIkeEagle** [comment]
Someone a simple example to reproduce this, just opened a few large arrays in nvim without an issue

**Comment by perotta** [comment]
Hi @Dornat did you find a solution for this? I'm having the same problem. I don't know exactly how to reproduce it niether
