### ISSUE TITLE
Type Error when I try to start debugging session

### ISSUE THREAD

**Issue by Raensul** [vim-vdebug/vdebug#434]
TypeError on master branch while trying to start debugging session.

```
An error occured: <class 'TypeError'>
Traceback (most recent call last):
  File "/Users/rnsl/.vim/bundle/vdebug/python3/vdebug/event.py", line 722, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/Users/rnsl/.vim/bundle/vdebug/python3/vdebug/event.py", line 275, in run
    status_str = str(status)
TypeError: __str__ returned non-string (type NoneType)
```
macbook pro, MacOS Catalina:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 26 2019 21:43:31)
macOS version
Included patches: 1-2350
Compiled by Homebrew
```
It might be related to https://github.com/vim-vdebug/vdebug/issues/362

**Comment by BlackIkeEagle** [comment]
thanks I'll have to add more checks there
