### ISSUE TITLE
Error after close an empty breakpoint window

### ISSUE THREAD

**Issue by przepompownia** [vim-vdebug/vdebug#451]
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 05 2020 03:20:13)                                                      
Included patches: 1-510
```
Error detected while processing BufWinLeave Autocommands for "DebuggerBreakpoints":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/debugger_interface.py", line 114, in mark_window_as_closed
    self.session_handler.ui().mark_window_as_closed(window)
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/ui/vimui.py", line 173, in mark_window_as_closed
    self.windows.window(name).mark_as_closed()
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/ui/vimui.py", line 533, in mark_as_closed
    self.destroy()
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/ui/vimui.py", line 598, in destroy
    vim.command('bwipeout %s' % self.name)
vim.error: Vim(bwipeout):E937: Attempt to delete a buffer that is in use: DebuggerBreakpoints
```

**Comment by przepompownia** [comment]
Similar error is thrown after closing one of Vdebug window before closing connection. 

Maybe these buffers should become hidden instead of trying to destroy them prematurely?
