### ISSUE TITLE
neovim: dd on breakpoint window does not work

### ISSUE THREAD

**Issue by przepompownia** [vim-vdebug/vdebug#452]
```
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 8 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/debugger_interface.py", line 80, in handle_delete_line_keypress
    return self.event_dispatcher.delete_line(self.session_handler)
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/event.py", line 807, in delete_line
    RemoveBreakpointEvent(session).run(id)
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/event.py", line 628, in run
    self.session_handler.breakpoints().remove_breakpoint_by_id(id)
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/breakpoint.py", line 83, in remove_breakpoint_by_id
    self.breakpoints[id].on_remove()
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/breakpoint.py", line 148, in on_remove
    self.ui.remove_breakpoint(self)
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/ui/vimui.py", line 295, in remove_breakpoint
    self.windows.breakpoints().remove_breakpoint(id)
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/ui/vimui.py", line 651, in remove_breakpoint
    self._buffer.delete(i)
  File "/home/user/.vim/pack/bundle/opt/vdebug/python3/vdebug/ui/vimui.py", line 447, in delete
    self._buffer[end_line]
  File "/home/user/.local/lib/python3.8/site-packages/pynvim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/home/user/.local/lib/python3.8/site-packages/pynvim/api/common.py", line 58, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Index out of bounds
```

**Comment by BlackIkeEagle** [comment]
I've started looking into this and this is really annoying to fix. I currently don't really know how to deal with it because the behaviour between vim and neovim is different, and I don't yet see a way to align it.
