### ISSUE TITLE
Run to, step in, step over: Vim(sign):E474: Invalid argument 

### ISSUE THREAD

**Issue by BasCostBudde** [vim-vdebug/vdebug#466]
I just installed the plugin into my vim 8.0 using pathogen. I start a session with F5, just fine, and want to run to the first breakpoint by F9. This gives me the error 474.

Error detected while processing :
Traceback (most recent call last):
  File "/home/bas/.vim/bundle/vdebug/python3/vdebug/event.py", line 779, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/bas/.vim/bundle/vdebug/python3/vdebug/event.py", line 304, in run
    self.session.cur_lineno)
  File "/home/bas/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 236, in set_source_position
    self.sourcewin.place_pointer(lineno)
  File "/home/bas/.vim/bundle/vdebug/python3/vdebug/ui/vimui.py", line 392, in place_pointer
    % (self.pointer_sign_id, line, self.file))
vim.error: Vim(sign):E474: Invalid argument

(a couple of exceptions follow in this trace). Then the source window actually moves to the first breakpoint, and an extra log window opens.
Stepping into the next line also causes an error, followed by the source window being updated--but now I do not see a line pointer.

Where to go from here?

**Comment by jmarsman** [comment]
Try to update your vim to 8.2. 

vdebug is trying to set a priority on a sign, which is not supported by vim 8.0

**Comment by BasCostBudde** [comment]
Splendid!
