### ISSUE TITLE
Vdebug and <class 'neovim.api.nvim.NvimError'> error

### ISSUE THREAD

**Issue by VoltairedesChamps** [vim-vdebug/vdebug#480]
Hello, i'm new to this environnment, i come from vscode background but the thing is i find it very slow so i wanted to do this with vim as im appreciating the shortkeys,  i have wsl and xdebug who is install on wamp. 
If i understand right i can communicate with my wsl where i have nvim on it and the xdebug server on wamp.

I installed python3 on wsl and i can run the debugging as it seems to interract with the php (it's slowing down the process )
but i have this error that i can't understand : 
```

- [Debug] {Mon 31 2020 10:09:14} Available context names: {0: 'Locals', 1: 'Superglobals'}
- [Info] {Mon 31 2020 10:09:14} Updated line number of breakpoint 11000 to 13830
- [Info] {Mon 31 2020 10:09:14} Updated line number of breakpoint 11001 to 13835
- [Info] {Mon 31 2020 10:09:14} Registering 2 breakpoints with the debugger
- [Debug] {Mon 31 2020 10:09:14} Command: breakpoint_set -i 2 -t line -f "file:///mnt/c/wamp/www/website2/app/Controller/WalletsController.php" -n 13830 -s enabled
- [Debug] {Mon 31 2020 10:09:14} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="2" state="enabled" id="76040004"></response>
- [Debug] {Mon 31 2020 10:09:14} Command: breakpoint_set -i 3 -t line -f "file:///mnt/c/wamp/www/website2/app/Controller/WalletsController.php" -n 13835 -s enabled
- [Debug] {Mon 31 2020 10:09:14} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="3" state="enabled" id="76040005"></response>
- [Debug] {Mon 31 2020 10:09:14} starting with step_into (break_on_open = 1)
- [Debug] {Mon 31 2020 10:09:14} Command: step_into -i 4
- [Debug] {Mon 31 2020 10:09:14} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="step_into" transaction_id="4" status="break" reason="ok"><xdebug:message filename="file:///C:/wamp/www/website2/app/webroot/index.php" lineno="20"></xdebug:message></response>
- [Debug] {Mon 31 2020 10:09:14} refresh event
- [Info] {Mon 31 2020 10:09:14} Dispatching refresh event
- [Debug] {Mon 31 2020 10:09:14} ** RefreshEvent
- [Info] {Mon 31 2020 10:09:14} Getting stack information
- [Debug] {Mon 31 2020 10:09:14} keymapper: reload_keys
- [Debug] {Mon 31 2020 10:09:14} Command: stack_get -i 5
- [Debug] {Mon 31 2020 10:09:14} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="5"><stack where="{main}" level="0" type="file" filename="file:///C:/wamp/www/website2/app/webroot/index.php" lineno="20"></stack></response>
- [Info] {Mon 31 2020 10:09:14} Moving to current position in source window
- [Info] {Mon 31 2020 10:09:14} Setting source file: C:\wamp\www\website2\app\webroot\index.php
- [Debug] {Mon 31 2020 10:09:14} Setting source line number: 20
- [Info] {Mon 31 2020 10:09:14} Placing pointer sign on line 20
- [ERROR] {Mon 31 2020 10:09:14} **An error occured: <class 'neovim.api.nvim.NvimError'>**
Traceback (most recent call last):
  File "/home/raheel/.config/nvim/plugged/vdebug/python3/vdebug/event.py", line 784, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/raheel/.config/nvim/plugged/vdebug/python3/vdebug/event.py", line 309, in run
    self.session.cur_lineno)
  File "/home/raheel/.config/nvim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 236, in set_source_position
    self.sourcewin.place_pointer(lineno)
  File "/home/raheel/.config/nvim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 396, in place_pointer
    vim.command(signstr % (self.pointer_sign_id, line, self.file))
  File "/usr/lib/python3/dist-packages/neovim/api/nvim.py", line 285, in command
    return self.request('nvim_command', string, **kwargs)
neovim.api.nvim.NvimError: b'Vim(sign):E474: Invalid argument'

- [Debug] {Mon 31 2020 10:09:52} keymapper: reload_keys
- [Info] {Mon 31 2020 10:09:52} Closing the connection
- [Debug] {Mon 31 2020 10:09:52} Command: stop -i 6
- [Debug] {Mon 31 2020 10:09:52} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="6" status="stopped" reason="ok"></response>
- [Debug] {Mon 31 2020 10:09:52} Closing the socket
- [Debug] {Mon 31 2020 10:09:52} Closing the socket
- [Debug] {Mon 31 2020 10:09:52} Closing the socket
```

I hope somebody has a solution to it.

Thanks in advance !

**Comment by BlackIkeEagle** [comment]
Could you tell what version of neovim you use?

**Comment by VoltairedesChamps** [comment]
I use NVIM v0.3.4 .

**Comment by BlackIkeEagle** [comment]
And you have latest master? I thought I fixed that in https://github.com/vim-vdebug/vdebug/commit/c7a2a7231bc7aec0b33b35e8d080bcd3e1baf8ab

**Comment by VoltairedesChamps** [comment]
My bad, i upgraded to the last version on testing 0.44 and i don't have the problem anymore.  Thanks a lot will now see the video to learn about the tool.
