### ISSUE TITLE
Xdebug 3 support

### ISSUE THREAD

**Issue by cprn** [vim-vdebug/vdebug#497]
Hi. I updated `xdebug` from 2.9.8 to 3.0.2 and it started giving this error on almost every step, sometimes straight away when I start debugging:

```
- [ERROR] {Thu 14 2021 17:05:28} An error occured: <class 'UnicodeDecodeError'>
Traceback (most recent call last):
  File "/home/user/.vim/plugged/vdebug/python3/vdebug/event.py", line 784, in dispatch_event
    Dispatcher.events[name](self.__session_handler).run(*args)
  File "/home/user/.vim/plugged/vdebug/python3/vdebug/event.py", line 660, in run
    self.ui.windows.watch().accept_renderer(rend)
  File "/home/user/.vim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 619, in accept_renderer
    self.write(renderer.render())
  File "/home/user/.vim/plugged/vdebug/python3/vdebug/ui/vimui.py", line 910, in render
    properties = self.response.get_context()
  File "/home/user/.vim/plugged/vdebug/python3/vdebug/dbgp.py", line 125, in get_context
    self.create_properties(ContextProperty(c))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 1023: unexpected end of data
```

I'm trying to prepare a minimal example that triggers it but nothing "simple" seems to be working so I decided to ask - is this a known issue? The error doesn't prevent following the code step by step but the variable context is empty and pressing `<F11>` triggers same error again.

**Comment by vlada-dudr** [comment]
It can be easy reproduced by reading binary file content into variable.
