### ISSUE TITLE
No option with key 'autostart'

### ISSUE THREAD

**Issue by nrob81** [vim-vdebug/vdebug#507]
Hello, i getting this error on pressing <F5> or calling :VdebugStart in neovim:

Vdebug will wait for a connection in the background                                         
Error detected while processing function provider#python3#Call:                                                                                                                   
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/debugger_interface.py", line 47, in run
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 67, in run
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 44, in listen
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 52, in start_listener
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/listener.py", line 51, in start
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/opts.py", line 32, in get
vdebug.opts.OptionsError: No option with key 'auto_start'
Press ENTER or type command to continue

on the 2nd try I get this:
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/debugger_interface.py", line 47, in run
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 67, in run
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 44, in listen
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/session.py", line 47, in start_listener
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/listener.py", line 12, in create
  File "/home/nrob/.config/nvim/plugged/vdebug/pythonx/vdebug/opts.py", line 32, in get
vdebug.opts.OptionsError: No option with key 'background_listener'
Press ENTER or type command to continue

my vdebug config is:
  1   let g:vdebug_options= {                                                                                         
  2   \    "port" : 9003,                                                                                                                              
  3   \    "server" : 'localhost',                                                                                                                     
  4   \    "timeout" : 20,                                                                                                                             
  5   \    "on_close" : 'detach',                                                                                                                      
  6   \    "break_on_open" : 1,                                                                                                                        
  7   \    "ide_key" : '',                                                                                                                             
  8   \    "path_maps" : {"/var/www/html": "/home/nrob/www/rest"},                                                                                     
  9   \    "debug_window_level" : 0,                                                                                
 10   \    "debug_file_level" : 2,                                                                                  
 11   \    "debug_file" : "/home/nrob/vdebug.log",                                                                       
 12   \    "watch_window_style" : 'compact',                                                                                 
 13   \    "marker_default" : '⬦',                                                                                        
 14   \    "marker_closed_tree" : '▸',                                                                                    
 15   \    "marker_open_tree" : '▾'                                                                                 
 16   \ }     

my php is in docker container, the xdebug (3.0.4) config is:
xdebug.mode=debug
xdebug.client_host=172.17.0.1
xdebug.start_with_request=1

in the xdebug_info() generated page, i see there notices:
[Step Debug] Creating socket for '172.17.0.1:9003', poll success, but error: Operation now in progress (29).	
[Step Debug] Could not connect to debugging client. Tried: 172.17.0.1:9003  (through xdebug.client_host/xdebug.client_port) :-(

Can you please help me with this? Thanks

**Comment by nrob81** [comment]
ok, i figured it out. :)

```
-let g:vdebug_options= {
-  \    "port" : 9003,
-  \    "server" : 'localhost',
-  \    "timeout" : 20,
-  \    "on_close" : 'detach',
-  \    "break_on_open" : 1,
-  \    "ide_key" : '',
-  \    "path_maps" : {"/var/www/html": "/home/nrob/www/project"},
-  \    "debug_window_level" : 0,
-  \    "debug_file_level" : 2,
-  \    "debug_file" : "/tmp/vdebug.log",
-  \    "watch_window_style" : 'compact',
-  \    "marker_default" : '⬦',
-  \    "marker_closed_tree" : '▸',
-  \    "marker_open_tree" : '▾'
-  \ }

+let g:vdebug_options.port = 9003
+let g:vdebug_options.path_maps = {"/var/www/html": getcwd()}
```

I had a config with the whole vdebug_options and overwrote the default options.
I got my error because i didn't had the auto_start property.

hope it is helpful to someone
